INSERT INTO UTENTE (ID, USERNAME, PASSWORD, USERTYPE) VALUES (1, 'admin', '$2y$12$p9Cz.BwmxMoRPYhHuLDW5edhEYeZTtF0X7BzRKbABj4rDwE5GGoJG', 0);
INSERT INTO UTENTE (ID, USERNAME, PASSWORD, USERTYPE) VALUES (2, 'bob', 'user', 1);
INSERT INTO UTENTE (ID, USERNAME, PASSWORD, USERTYPE) VALUES (3, 'ted', 'user', 1);